default: &default
  appid: wx1c4395f4a17baa83s
  secret: 651e2f71c1f39005a02185994566b210
#  token: wechat
#  agentid:  1
# Or if using public account, only need above two line
#  appid: "my_appid"
#  secret: "my_secret"
  token:    "wechat"
  access_token: "./wechat_access_token"
  encrypt_mode: false # if true must fill encoding_aes_key
  encoding_aes_key:  "Yn35Ut37Gc0ZhMpadhoVn6hPzjxokdFYqRPk6aKKjU6"
  jsapi_ticket: "./wechat_jsapi_ticket"

production:
#  corpid:     <%= ENV['WECHAT_CORPID'] %>
#  corpsecret: <%= ENV['WECHAT_CORPSECRET'] %>
#  agentid:    <%= ENV['WECHAT_AGENTID'] %>
# Or if using public account, only need above two line
  appid: wx1c4395f4a17baa83s
  secret:
  token: wechat
  timeout:    30,
  skip_verify_ssl: true
  access_token:  <%= ENV['WECHAT_ACCESS_TOKEN'] %>
  encrypt_mode: false # if true must fill encoding_aes_key
  encoding_aes_key:  <%= ENV['WECHAT_ENCODING_AES_KEY'] %>
  jsapi_ticket: <%= ENV['WECHAT_JSAPI_TICKET'] %>
  oauth2_cookie_duration: <%= ENV['WECHAT_OAUTH2_COOKIE_DURATION'] %> # seconds

development:
  <<: *default
  trusted_domain_fullname: "http://pansheng.ilibrary.me"

test:
  <<: *default

# Multiple Accounts
#
# wx2_development:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#  access_token: "tmp/wechat_access_token2"
#  jsapi_ticket: "tmp/wechat_jsapi_ticket2"
#
# wx2_test:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx2_production:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx3_development:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#  access_token: "tmp/wechat_access_token3"
#  jsapi_ticket: "tmp/wechat_jsapi_ticket3"
#
# wx3_test:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx3_production:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#